version: "3.9"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: react_php_app
      DB_USERNAME: root
      DB_PASSWORD: root
    command: sh -lc "composer install --no-interaction --prefer-dist --no-progress && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react_php_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  react_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: ["npm", "run", "dev"]
    # uncomment if you want live reload during development
    # volumes:
    #   - ./client:/app

volumes:
  db_data:
  vendor:
