version: "3.9"
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react_php_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  react_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "5173:5173"
    # Option 1: Comment out the volume if you want to rely on the image
    # volumes:
    #   - ./client:/app
    depends_on:
      - app
    command: ["npm", "run", "dev"]

volumes:
  db_data:
