name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: react_php_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install Laravel dependencies
        run: |
          cd server
          composer install --no-interaction --prefer-dist

      - name: Set Laravel APP_KEY
        run: |
          cd server
          if [ ! -f .env ]; then cp .env.example .env; fi
          php artisan key:generate

      - name: Install React dependencies
        run: |
          cd client
          npm install

      - name: Run Laravel tests
        run: |
          cd server
          php artisan test

      - name: Run React build
        run: |
          cd client
          npm run build
